name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [ linux, windows ]
    env:
      GOOS: ${{ matrix.goos }}
      CGO_ENABLED: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: FirelightFlagboy/gh-runner-free-disk-space@main

      - name: Initialization environment
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq upgrade
          sudo -E apt-get -yqq autoremove
          sudo -E apt-get -yqq autoclean
          sudo -E apt-get -yqq clean
          sudo -E systemctl daemon-reload

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Get Dependencies
        run: go mod download

      - name: Build Xray
        if: matrix.goos != 'windows'
        run: |
          mkdir -p build
          go build -o build/xray -trimpath -ldflags "-s -w -buildid=" ./main

      - name: Build Xray for Windows
        if: matrix.goos == 'windows'
        run: |
          mkdir -p build
          go build -o build/xray.exe -trimpath -ldflags "-s -w -buildid=" ./main

      - name: Delete old Releases and Workflows
        if: matrix.goos == 'linux'
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 1
          gh_token: ${{secrets.GITHUB_TOKEN}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Xray-${{ matrix.goos }}
          path: build/

      - name: Zip
        run: |
          cd ./build
          zip -r Xray-${{ matrix.goos }}.zip .

      - name: Release Firmware
        if: matrix.goos == 'linux'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Xray-${{ matrix.goos }}
          files: build/Xray-${{ matrix.goos }}.zip
