name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        goos: [ linux, windows ]
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare
        run: sudo apt-get update

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: Get Dependencies
        run: go mod download

      - name: Build Xray
        if: matrix.goos != 'windows'
        run: |
          mkdir -p build
          go build -v -o build/xray -trimpath -ldflags "-s -w -buildid=" ./main

      - name: Build Xray for Windows
        if: matrix.goos == 'windows'
        run: |
          mkdir -p build
          go build -v -o build/xray.exe -trimpath -ldflags "-s -w -buildid=" ./main

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Xray-${{ matrix.goos }}
          path: build/
